name: Build and Deploy from ph-pages to gh-pages

on:
  push:
    branches:
      - ph-pages

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source branch (ph-pages)
        uses: actions/checkout@v3
        with:
          ref: ph-pages
